#!/bin/sh
#

# PROVIDE: increscent

. /etc/rc.subr

name="increscent"
rcvar="${name}_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-c -f -P ${pidfile} -r /home/robert/increscent/increscent.js"

load_rc_config $name
run_rc_command "$1"
